name: nba_go
description: An unofficial NBA app.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.20.0
  equatable: ^0.3.0
  http: ^0.12.0+2
  auto_size_text: ^2.0.2+1
  intl: ^0.15.8
  flutter_spinkit: ^3.1.0
  bottom_navy_bar: ^5.2.0
  line_icons: ^0.2.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/splash.png
   - assets/logos/
   - assets/player_placeholder.png
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 600
    - family: OpenSansCondensed
      fonts:
        - asset: assets/fonts/OpenSansCondensed-LightItalic.ttf
          style: italic
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 600
